Repository Team-GONG-BAEK/gong-baek-iOS, pull requests merged in 2025-03, with the labels that each got.

#5 [Feat] #4 탭 바 수정
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/Common/CustomTabBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TabBarState.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/AddMeetingView.swift
Labels: 🧩 Feat, 🤯 희은

#7 [Feat] #1 - 마이페이지 UI 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/xcshareddata/xcschemes/Gongbaek_iOS.xcscheme
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/MyPageSegmentControlBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TabBarState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/TabBarView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyFilling/View/MyFillingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/MyPageViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyFillingEmptyCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyFillingHeader.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyFillingList.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyPageView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyProfile.swift
Labels: 🧩 Feat, 🧤 민서

#8 [Feat] #3 - 애플 로그인 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/AgreementListCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Text/MultiColoredText.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/AgreeState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/PlatformType.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Manager/TokenInterceptor.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Manager/TokenManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/LoginNavigationView.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/RootViewSwitcher.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/check_fill_32.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/check_fill_32.imageset/btn_check_fill_32.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/check_gray_32.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/check_gray_32.imageset/btn_check_gray_32.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/check_unfill_32.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/check_unfill_32.imageset/btn_check_unfill_32.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/img_apple_logo.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/img_apple_logo.imageset/.svg
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/img_logo.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Login/img_logo.imageset/img_logo.svg
  Gongbaek_iOS/Gongbaek_iOS/Gongbaek_iOS.entitlements
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/APIConstants.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Auth/PatchReissueResponse.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Auth/PostSigninRequestDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Auth/PostSigninResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/Providers.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/AuthTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/CommentTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/FillingTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/HomeTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/MeetingDetailTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/MeetingRoomTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/LoginViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/View/AgreementView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/View/AppleLoginButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/View/LoginView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Onboarding/OnboardingView.swift
Labels: 🧩 Feat, 🧤 민서

#10 [Network] #9 - 마이페이지 서버 통신
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/MyPage/GetFillingResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/MyPage/GetMyFillingResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/MyPage/GetMyProfileResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/MyPage/GetTimeTableResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/MyPage/PostMeetingRequestDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/Providers.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/FillingTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/MyPageTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/MyPageViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyPageView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyProfile.swift
Labels: 🧤 민서, 🌐 Network
