Repository Team-GONG-BAEK/gong-baek-iOS, pull requests merged in 2025-04, with the labels that each got.

#14 [Fix] #11 - 채우기 UI 수정
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/MeetingChipState.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingEmptyView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingList.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingView.swift
Labels: 🧤 민서, 🛠️ Fix

#13 [Feat] - #6 마이페이지 설정 UI 생성 및 WebView 연결
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/MyPageSettingEnums.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TabBarState.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/MyPageSetting/Model/MyPageSettingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/MyPageSetting/View/MyPageSettingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/MyPageSetting/View/SettingBasicCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/MyPageSetting/View/SettingHeaderCell.swift
Labels: 🧩 Feat, 🤯 희은

#19 [Feat] - #18 약관 동의 WebView 연결
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/AgreementListCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/AgreeState.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/View/AgreementView.swift
Labels: 🧩 Feat, 🧤 민서

#21 [Feat] - #20 로그인 관련 로직 구현
  Gongbaek_iOS/Gongbaek_iOS.xcodeproj/project.pbxproj
  Gongbaek_iOS/Gongbaek_iOS/Application/Gongbaek_iOSApp.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Alert/CustomAlert.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/MyPageSettingEnums.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TabBarState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/UserType.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Manager/TokenManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationDestination.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Mypage/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Mypage/ic_setting_48.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Image/Mypage/ic_setting_48.imageset/ic_setting_48.svg
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/VoidResult.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/Providers.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/AuthTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/LoginViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/View/AgreementView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/View/LoginView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/MyPageSetting/View/MyPageSettingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyPageView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPageSetting/Model/MyPageSettingModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPageSetting/View/MyPageSettingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPageSetting/View/SettingBasicCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPageSetting/View/SettingHeaderCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPageSetting/ViewModel/MyPageSettingViewModel.swift
Labels: 🧩 Feat, 🧤 민서

#27 [Fix] #26 - 토큰 재발급 로직 수정
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/MyPageSegmentControlBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Manager/TokenInterceptor.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Manager/TokenManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/APIConstants.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/Providers.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/AuthTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/SignupTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyPageView.swift
Labels: 🧤 민서, 🛠️ Fix

#29 [Chore] #17 - 탭 바 상단 스트로크 추가
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/Common/CustomTabBar.swift
Labels: 🤯 희은, 🏠 Chore
