Repository Team-GONG-BAEK/gong-baek-iOS, pull requests merged in 2025-05, with the labels that each got.

#32 [Feat] #25 - 회원가입 과정 내의 API 연결 및 에러 대응
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/CustomTextEditor.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/CustomTextFieldWithStatus.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TextFieldType.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Manager/TokenManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Base/NetworkProvider.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Environment/APIConstants.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Signup/PostSignupRequestDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/SignupTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/LoginViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolEmailVerificationView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/ViewModel/SignupViewModel.swift
Labels: 🧩 Feat, 🎐 나연, 🌐 Network, 🌱 Refactor

#34 [Chore] #12 - 내비게이션 바 UI 수정 및 내비게이션 매니저 싱글톤 패턴으로 변경
  Gongbaek_iOS/Gongbaek_iOS/Application/Gongbaek_iOSApp.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/Common/CustomNavigationBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/View+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Manager/TokenInterceptor.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Navigation/NavigationManager.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_report_48.imageset/Contents.json
  Gongbaek_iOS/Gongbaek_iOS/Global/Resource/Assets.xcassets/Icon/ic_report_48.imageset/ic_report_48.svg
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/AddMeetingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CategorySelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/IntroduceInput.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/LocationInput.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/WeekDaySelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Filling/View/FillingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Home/View/HomeView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/View/AgreementView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/View/LoginView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingDetailView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/View/MeetingRoomView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyPageView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPageSetting/View/MyPageSettingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Onboarding/OnboardingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolMajorSearchView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupView.swift
Labels: 🎐 나연, 🏠 Chore, 🌱 Refactor

#30 [Feat] - #16 MeetingDetailView 수정 및 구현
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Alert/BasicAlert.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Alert/GongbaekAlert.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/MemberProfileBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/OwnerProfileBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/MeetingDetail/GetOwnerInfoResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/AddMeetingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingDetailView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/ViewModel/MeetingDetailViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/View/MeetingRoomView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/ViewModel/MeetingRoomViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPageSetting/View/MyPageSettingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPageSetting/ViewModel/MyPageSettingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SchoolMajorSearchView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/View/SignupView.swift
Labels: 🧩 Feat, 🤯 희은

#36 [Fix] #35 - 자체 QA 사항 반영
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/ApplyBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Bar/Common/CustomNavigationBar.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Box/OwnerProfileBox.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Button/CategoryImageButton.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/Chip/MeetingChip.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/CommentCell.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/CommentList.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/CustomTextEditor.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/MeetingChipState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Extension/Date+.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Util/KeyboardObserver.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Comment/DeleteCommentRequestDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/DTO/Comment/GetCommentsResponseDTO.swift
  Gongbaek_iOS/Gongbaek_iOS/Network/Service/TargetType/CommentTargetType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/AddMeetingView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CalendarSelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CategorySelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/CoverImageSelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/LocationInput.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/TimeSelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/WeekDaySelect.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/ViewModel/AddMeetingViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Login/LoginViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/View/MeetingDetailView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingDetail/ViewModel/MeetingDetailViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/View/MeetingRoomView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MeetingRoom/ViewModel/MeetingRoomViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyPageView.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/View/MyProfile.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/Signup/ViewModel/SignupViewModel.swift
Labels: 🎐 나연, 🛠️ Fix, 🏠 Chore

#41 [Fix] #37 - 1차 QA 수정사항 반영
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/List/MeetingInfoBase.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Component/TextField/CustomTextField.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/MeetingChipState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/MeetingInfoState.swift
  Gongbaek_iOS/Gongbaek_iOS/Global/Enum/TextFieldType.swift
  Gongbaek_iOS/Gongbaek_iOS/Presentation/AddMeeting/View/LocationInput.swift
Labels: 🧤 민서, 🛠️ Fix
